import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Header } from "@/components/home/Header";
import { Footer } from "@/components/home/Footer";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `${spaceGrotesk.variable} antialiased font-font-space-grotesk`,
          spaceGrotesk.className
        )}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
